[licenses]
version = 2

# We want really high confidence when inferring licenses from text
confidence-threshold = 0.93

# Commented license types are allowed but not currently used
allow = [
    "Apache-2.0",
    # "BSD-2-Clause",
    "BSD-3-Clause",
    "BSL-1.0",
    # "CC0-1.0",
    "ISC",
    "MIT",
    "OpenSSL",
    "Unlicense",
    "Zlib",
    "MPL-2.0",
]

exceptions = [

]

[bans]
# Deny multiple versions or wildcard dependencies.
multiple-versions = "deny"
wildcards = "deny"

deny = []

skip = [

]

skip-tree = [

]

[bans.workspace-dependencies]
duplicates = "deny"
include-path-dependencies = true
unused = "deny"

[advisories]
# generational-arena is currently unmaintained.
ignore = [
    "RUSTSEC-2024-0014",
]

[sources]
# Deny crates from unknown registries or git repositories.
unknown-registry = "deny"
unknown-git = "deny"

allow-git = [

]
